name: Issue Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: 📋 Issue description
      placeholder: Issue description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 🐾 Steps to reproduce
      placeholder: |
        1. Enter Wordbox section
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 🔎 Expected result
      placeholder: Expectations
  - type: textarea
    id: screenshots
    attributes:
      label: 📎 Attach any screenshots or videos
      placeholder: Screen captures/ Screen recordings
  - type: textarea
    id: log
    attributes:
      label: ✏️ Log related to issue
      placeholder: Paste sending and recieved from log console related to issue
  - type: dropdown
    id: section
    attributes:
      label: 📌 App section impacted (can be multiple)
      options:
        - "Onboarding"
        - "Home"
        - "Lessons"
        - "Boss"
        - "Hashtags"
        - "Dictionary"
        - "Leaderboards"
        - "Missions"
        - "Medals"
        - "Streaks"
        - "Interests"
        - "Boxes"
        - "Avatars"
        - "Settings"
        - "Subscriptions"
        - "Other"
      multiple: true
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue!
